[package]
name = "socklist"
version = "0.1.0"
authors = ["Yuri Geinish <wi1em@protonmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.35"
atty = "0.2.14"
clap = "2.33.3"
netstat2 = "0.9.1"
sysinfo = "0.15.3"
termcolor = "1.1.2"
